package agentflow.model;

import java.util.Collections;
import java.util.List;

/**
 * Encapsulates the verification outcome generated by the VerifierAgent.
 */
public record VerificationResult(
        boolean passed,
        int score, // 0 to 100
        String summary,
        List<String> checklist,
        List<String> issues,
        boolean requiresReplanning
) {
    public VerificationResult {
        checklist = checklist != null ? Collections.unmodifiableList(checklist) : Collections.emptyList();
        issues = issues != null ? Collections.unmodifiableList(issues) : Collections.emptyList();
    }

    public static VerificationResult success(int score, String summary, List<String> checklist) {
        return new VerificationResult(true, score, summary, checklist, Collections.emptyList(), false);
    }

    public static VerificationResult failure(int score, String summary, List<String> checklist, List<String> issues, boolean replan) {
        return new VerificationResult(false, score, summary, checklist, issues, replan);
    }
}
